### ISSUE TITLE
error setting up

### ISSUE THREAD

**Issue by Aaybob** [mddub/pancreabble#10]
I don't have pancreoptions.json in myopenaps2
Using cp src/oref0/lib/oref0-setup/pancreoptions.json myopenaps2
Then running :~/myopenaps2# ~/src/oref0/bin/peb-urchin-status.sh
Usage: grep [OPTION]... PATTERN [FILE]...
Try 'grep --help' for more information.
Missing dev parameter

#  rfcomm show hci0
rfcomm0: 6D:0B:D3:64:00:08 channel 1 clean

#!/bin/bash
MAC=$1
if ! ( rfcomm show hci0 | grep -q $MAC ) ; then

I'm quitting for now because I got paired to edison and pebble then found my watchface had been inadvertantly left on another and pairing edison pebble took some struggle and haven't gotten it paired to my second pebble, round.

**Comment by mddub** [comment]
It sounds like you're having an issue with the oref0 setup scripts, which are maintained by other folks here: https://github.com/openaps/oref0

I suggest you ask for support on Gitter: https://gitter.im/nightscout/intend-to-bolus
