### ISSUE TITLE
apt-get install jq

### ISSUE THREAD

**Issue by Aaybob** [mddub/pancreabble#11]
#apt-get update    has this error  is it an issue?
Ign http://http.debian.net jessie-backports/main i386 Packages/DiffIndex
Err http://security.debian.org jessie/updates/contrib Translation-en_IE
  Something wicked happened resolving 'security.debian.org:http' (-5 - No address associated with hostname)

**Comment by mddub** [comment]
This is an issue with oref0-setup.sh, not Pancreabble. I suggest you file an issue in oref0 if it persists. My first guess is that it's a transient error due to network problems.
