### ISSUE TITLE
Duration of data

### ISSUE THREAD

**Issue by hichameyessou** [mddub/pancreabble#7]
After invoking succesfully the reports and sending to the pebble the bg's/temp basals I have on my pebble all the data. But if I enter/open any other notification I lose every OpenAPS/bg related data.
Is everything normal or I am lacking something in the configuration?

**Comment by mddub** [comment]
Do you mean for Urchin? If so, that's intended behavior. Urchin remembers the last app message it received, but only while the app is open. If you close and reopen it, you'll have to wait until the next message is sent from your OpenAPS; then the graph and other data will be populated again. Does that match your experience?

**Comment by hichameyessou** [comment]
Yep, right! It would be nice to have the data to be persistent, but I think is gonna be a lot more complex

**Comment by mddub** [comment]
Yep, persisting the last message between app loads is on the roadmap for Urchin, but probably won't happen too soon.

For now, with Pancreabble, you could always use both Urchin and notifications, so that if you really want to know this instant, you can check your notifications list.
